### ISSUE TITLE
README corrections

### ISSUE THREAD

**Issue by AndrewNute** [OdyOSG/oncoRegimens#31]
I think output_processed shown in the screenshot from the README instructions is actually supposed to be processedAll (or vice versa) from the cell above it?  

![image](https://github.com/OdyOSG/ARTEMIS/assets/43183213/bfab546a-1592-44d0-aea1-b7a39758526c)

**Also**

From the output section in the screenshot below, I think this writeOutputs command needs a regGroups argument for the last four arguments to correctly match their default positional placement in the writeOutputs function.

![image](https://github.com/OdyOSG/ARTEMIS/assets/43183213/69a8b548-13ce-437a-8b33-2cf97f6c4573)

**Comment by laurencelawrencearcher** [comment]
Great! Updated, thank you
