### ISSUE TITLE
Errors in  writeOutputs

### ISSUE THREAD

**Issue by dimshitc** [OdyOSG/oncoRegimens#36]
Error in writeOutputs in the readme
currently it's, but should be
writeOutputs(output_all, processedAll = processedAll, processedEras = processedEras,
             connectionDetails = connectionDetails, cdmSchema = cdmSchema,
             regGroups = regGroups, regStats = regStats, stringDF = stringDF, 
             con_df = con_df)

writeOutputs(output_all, **output_processed**= processedAll, processedEras = processedEras,
             connectionDetails = connectionDetails, cdmSchema = cdmSchema,
             regGroups = regGroups, regStats = regStats, stringDF = stringDF, 
             con_df = con_df)

then when running it on redshift database, it says:

i Generating cohort level stats...
Connecting using Redshift driver
Using Category, Gender as id variables
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `value[[3L]]()`:
! com.amazon.redshift.util.RedshiftException: ERROR: syntax error at or near ","
  Position: 37
Run `rlang::last_trace()` to see where the error occurred.

**Comment by laurencelawrencearcher** [comment]
Hi Dima, thanks for the issue and exploring the package.

This repo is an old and defunct version of ARTEMIS, you might want to check out:

https://github.com/OHDSI/ARTEMIS

For the up-to-date release. This may also solve the redshift exception as the reliance on databaseConnector is now updated, but if you do have the same error, I'd love to solve it, just go ahead and open a new issue on that repo or e-mail me.

**Comment by dimshitc** [comment]
Hi Laurence, 
I used the https://github.com/OHDSI/ARTEMIS to get the code and the readme. 
but this part
![image](https://github.com/user-attachments/assets/5e69f65d-e5d4-4ee5-9cc4-9cab230d9dc5)
has link to the old github issues
so I'll open this issue in the new repo
